ratings:
  - "**.php"

exclude_paths:
  - "vendor"
  - "Test/*"
  - ".git"

engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
