language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION="3.0.x-dev as 2.8"
  allow_failures:
    - env: SYMFONY_VERSION=2.7.*@dev
    - env: SYMFONY_VERSION=2.8.*@dev
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

after_script:
  - CODECLIMATE_REPO_TOKEN=aa842b55fe5c7c1ddab1feb20f04b51c8f7e58868a212d42e6c97bf76d635be7 ./vendor/bin/test-reporter

script: phpunit --coverage-clover build/logs/clover.xml

